### ISSUE TITLE
Please correct README.md to provide correct uses example

### ISSUE THREAD

**Issue by bnippercg** [dannevesdantas/set-version-assemblyinfo#1]
Currently on the readme it shows the following example usage:

```
- name: Set version on AssemblyInfo.cs
  uses: dannevesdantas/set-version-assemblyinfo-win@v1.0.0
  with:
    version: '3.2.0'
```

Please adjust to the `uses` to ensure it can be used as a cut-and-paste operation:
`uses: dannevesdantas/set-version-assemblyinfo@v.1.0.0`

Thank you for providing this action.
